openapi: 3.0.0
info:
  title: Social Media API
  version: 1.0.0
  description: API for managing a social media application database
servers:
  - url: 'https://api.yourdomain.com/v1'
paths:
  /users:
    post:
      summary: Create a new user
      operationId: createUser
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
      responses:
        '201':
          description: User created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '400':
          description: Invalid input provided
  /users/{userId}:
    get:
      summary: Get a user by ID
      operationId: getUserById
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
  /posts:
    post:
      summary: Create a new post
      operationId: createPost
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Post'
      responses:
        '201':
          description: Post created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Post'
        '400':
          description: Invalid input provided

components:
  schemas:
    User:
      type: object
      required:
        - username
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        telegram_id:
          type: integer
          format: int64
        username:
          type: string
        wallet:
          type: string
        profile_photo:
          type: string
        time_registration:
          type: string
          format: date-time
    Post:
      type: object
      required:
        - user_id
      properties:
        id:
          type: integer
          format: int64
          readOnly: true
        user_id:
          type: integer
          format: int64
        control_id:
          type: boolean
        balance_sheet_id:
          type: integer
        tag_id:
          type: integer
        link:
          type: string
        time_creation:
          type: string
          format: date-time

