import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import { AppProps } from "next/app";
import { NavigationBar } from "@/widgets/NavigationBar";

import { TelegramWebApp } from "@/app/providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function HomePage({ Component, pageProps }: AppProps) {
  return (
      <div className={`${inter.className} antialiased max-w-[420px]`}>
        <TelegramWebApp>
            <Component {...pageProps} />
            <NavigationBar />
        </TelegramWebApp>
      </div>
  );
}

export default HomePage;
