import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import { AppProps } from "next/app";
import { NavigationBar } from "@/widgets/NavigationBar";

import { WebAppProvider } from "@/app/providers/WebAppProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

function HomePage({ Component, pageProps }: AppProps) {
  return (
    <WebAppProvider>
      <div className={`${inter.className} antialiased max-w-[420px]`}>
        <Component {...pageProps} />
        <NavigationBar />
      </div>
    </WebAppProvider>
  );
}

export default HomePage;
