import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/app/styles/globals.css";
import { TelegramWebApp } from "@/app/providers/TelegramWebApp";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

function HomePage({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className={`${inter.className} antialiased`}>
            <TelegramWebApp>
                {children}
            </TelegramWebApp>
        </div>
    );
}

export default HomePage;
